[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixpkgsArchive = "nixpkgs-unstable"

[[build.nixpacksConfig.phases]]
name = "setup"
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[[build.nixpacksConfig.phases]]
name = "install"
cmds = ["cd backend && npm install"]

[start]
cmd = "cd backend && npm start"
